// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.masconsult.contacto.domain;

import eu.masconsult.contacto.domain.Contact;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ContactDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ContactDataOnDemand: @Component;
    
    private Random ContactDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Contact> ContactDataOnDemand.data;
    
    public Contact ContactDataOnDemand.getNewTransientContact(int index) {
        eu.masconsult.contacto.domain.Contact obj = new eu.masconsult.contacto.domain.Contact();
        obj.setEmail("email_" + index);
        obj.setFirstName("firstName_" + index);
        obj.setLastName("lastName_" + index);
        return obj;
    }
    
    public Contact ContactDataOnDemand.getSpecificContact(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Contact obj = data.get(index);
        return Contact.findContact(obj.getId());
    }
    
    public Contact ContactDataOnDemand.getRandomContact() {
        init();
        Contact obj = data.get(rnd.nextInt(data.size()));
        return Contact.findContact(obj.getId());
    }
    
    public boolean ContactDataOnDemand.modifyContact(Contact obj) {
        return false;
    }
    
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void ContactDataOnDemand.init() {
        if (data != null && !data.isEmpty()) {
            return;
        }
        
        data = eu.masconsult.contacto.domain.Contact.findContactEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Contact' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<eu.masconsult.contacto.domain.Contact>();
        for (int i = 0; i < 10; i++) {
            eu.masconsult.contacto.domain.Contact obj = getNewTransientContact(i);
            obj.persist();
            data.add(obj);
        }
    }
    
}
